name: ludo_score
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7
#  add_to_cart_animation: ^2.0.3
  url_launcher: ^6.1.12
#  flutter_share:
  share_plus: ^7.0.2
  google_fonts: ^5.1.0
  just_audio: ^0.9.29
  provider: ^6.0.3
  simple_ripple_animation: ^0.0.3
  audioplayers: ^5.1.0
  shared_preferences: ^2.2.1
  win32: ^4.1.2
  flutter_inset_box_shadow: ^1.0.6
#  flutter_inset_box_shadow:
#  qr_flutter: ^4.1.0
  vibration: ^1.8.1
  http:
  flutter_widget_from_html: ^0.9.0+2
  confetti: ^0.7.0
  pinput: ^3.0.1
  fluttertoast:
  intl: ^0.18.1
  motion: ^1.4.0
  widget_and_text_animator: ^1.1.5
  firebase_storage:
  firebase_database:
  cloud_firestore:
  firebase_core:
#  cashfree_pg:
  flutter_cashfree_pg_sdk: ^2.2.4+42
  google_mobile_ads: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
#  fwfh_text_style:








  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/
    - assets/font/
    - assets/button/
    - assets/images/
    - assets/images/dice/
    - assets/images/crown/
    - assets/sounds/

  fonts:
    - family: acme
      fonts:
        - asset: assets/font/Acme-Regular.ttf

    - family: right
      fonts:
        - asset: assets/font/Righteous-Regular.ttf

